name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: SCA Scan
      env:
        PROD_API_KEY: ${{ secrets.PROD_API_KEY }}
      run: |
        echo "$PROD_API_KEY"
        curl https://raw.githubusercontent.com/CloudDefenseAI/cd/master/latest/cd-latest-linux-x64.tar.gz > /tmp/cd-latest-linux-x64.tar.gz 
        tar -C /tmp -xzf /tmp/cd-latest-linux-x64.tar.gz  && chmod +x /tmp/cdefense
        /tmp/cdefense
        /tmp/cdefense sca --lang python --api-key "$PROD_API_KEY" --project-name "Python-Github-Action-Test"
